language: rust
rust: stable

matrix:
  fast_finish: true
  include:
    - env: LLVM_VERSION=3.5 CLANG_VERSION=clang_3_5
      os: linux
      addons: &gcc
        apt:
          sources: [ "ubuntu-toolchain-r-test" ]
          packages: [ "gcc-5" ]

    - env: VERSION=7.0
      os: linux
      addons: *gcc
    - env: VERSION=7.0
      os: osx
    - name: "Xcode10"
      env: VERSION=6.0
      os: osx
      osx_image: xcode10
      before_install: true

before_install: sh ci/before_install.sh
script: CLANG_VERSION=$VERSION sh ci/script.sh
